public with sharing class TestDataObjectCreation extends TestDataBulk{
//To Do eventually Salesforce will be able extend multiple classes when this is possible extend TestDataUpdate also

//Additional functions can be built here that may not fit neatly into the framework 
//You may also want to incorporate functions from TestDataUpdate directly in here to provide a 1 class call for the entire framework

}